---
- name: "Install chezmoi"
  ansible.builtin.dnf:
    name: chezmoi
    state: present
  become: true

- name: "Initialize chezmoi"
  ansible.builtin.command:
    cmd: >
      chezmoi init {{ chezmoi_repo }}
  args:
    creates: "{{ ansible_facts.user_dir }}/.local/share/chezmoi"
